# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'otpsWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_otpwin(object):
    def setupUi(self, otpwin):
        otpwin.setObjectName("otpwin")
        otpwin.resize(1016, 862)
        otpwin.setStyleSheet("\n"
"QDialog {\n"
"    background-color:rgb(120, 82, 82);\n"
"}\n"
"QTextEdit {\n"
"    background-color:rgb(42, 42, 42);\n"
"    color: rgb(0, 255, 0);\n"
"}\n"
"QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"    \n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"}\n"
"QPushButton:disabled{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(57, 57, 57, 255), stop:1 rgba(77, 77, 77, 255));\n"
"}\n"
"QLineEdit {\n"
"    border-width: 1px; border-radius: 4px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    padding: 0 8px;\n"
"    color: rgb(255, 255, 255);\n"
"    background:rgb(100, 100, 100);\n"
"    selection-background-color: rgb(187, 187, 187);\n"
"    selection-color: rgb(60, 63, 65);\n"
"}\n"
"QLabel {\n"
"    color:black;    \n"
"}\n"
"QProgressBar {\n"
"    text-align: center;\n"
"    color: rgb(240, 240, 240);\n"
"    border-width: 1px; \n"
"    border-radius: 10px;\n"
"    border-color: rgb(58, 58, 58);\n"
"    border-style: inset;\n"
"    background-color:rgb(77,77,77);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-radius: 5px;\n"
"}\n"
"QMenuBar {\n"
"    background:rgb(82, 82, 82);\n"
"}\n"
"QMenuBar::item {\n"
"    color:rgb(223,219,210);\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background: transparent;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background:rgb(115, 115, 115);\n"
"}\n"
"QMenu::item:selected {\n"
"    color:rgb(255,255,255);\n"
"    border-width:2px;\n"
"    border-style:solid;\n"
"    padding-left:18px;\n"
"    padding-right:8px;\n"
"    padding-top:2px;\n"
"    padding-bottom:3px;\n"
"    background:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"}\n"
"QMenu::item {\n"
"    color:rgb(223,219,210);\n"
"    background-color:rgb(78,78,78);\n"
"    padding-left:20px;\n"
"    padding-top:4px;\n"
"    padding-bottom:4px;\n"
"    padding-right:10px;\n"
"}\n"
"QMenu{\n"
"    background-color:rgb(78,78,78);\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:rgb(247,246,246);\n"
"}\n"
"QTabWidget::pane {\n"
"        border-color: rgb(77,77,77);\n"
"        background-color:rgb(101,101,101);\n"
"        border-style: solid;\n"
"        border-width: 1px;\n"
"        border-radius: 6px;\n"
"}\n"
"QTabBar::tab {\n"
"    padding:2px;\n"
"    color:rgb(250,250,250);\n"
"      background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"    border-style: solid;\n"
"    border-width: 2px;\n"
"      border-top-right-radius:4px;\n"
"   border-top-left-radius:4px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(95, 92, 93, 255));\n"
"    border-bottom-color: rgb(101,101,101);\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"      background-color:rgb(101,101,101);\n"
"      margin-left: 0px;\n"
"      margin-right: 1px;\n"
"}\n"
"QTabBar::tab:!selected {\n"
"        margin-top: 1px;\n"
"        margin-right: 1px;\n"
"}\n"
"QCheckBox {\n"
"    color:rgb(223,219,210);\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"    background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 150), stop:1 rgba(93, 103, 113, 150));\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(180,180,180);\n"
"      background-color:qlineargradient(spread:pad, x1:0.5, y1:0.7, x2:0.5, y2:0.3, stop:0 rgba(87, 97, 106, 255), stop:1 rgba(93, 103, 113, 255));\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    border-width:1px;\n"
"    border-color: rgb(87, 97, 106);\n"
"      background-color:rgb(255,255,255);\n"
"}\n"
"QStatusBar {\n"
"    color:rgb(240,240,240);\n"
"}\n"
"QWidget#scrollAreaWidgetContents{\n"
"background-color:rgb(60,60,60);\n"
"}\n"
"QDialog{\n"
"background-color:rgb(20, 20, 20);\n"
"}\n"
"\n"
"QScrollArea{\n"
"background-color:rgb(20, 20, 20);\n"
"}\n"
"\n"
"QLabel{\n"
"color:white\n"
"}\n"
"\n"
"QLineEdit{\n"
"    text-align: center;\n"
"    color:white;\n"
"    font:10pt;\n"
"}\n"
"\n"
"QLineEdit#secret_field{\n"
"    text-align: center;\n"
"    color:black;\n"
"    font:8pt\n"
"}\n"
"")
        self.layoutWidget = QtWidgets.QWidget(otpwin)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 991, 831))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.main_layout.setContentsMargins(30, 0, 30, 0)
        self.main_layout.setHorizontalSpacing(7)
        self.main_layout.setVerticalSpacing(10)
        self.main_layout.setObjectName("main_layout")
        self.body = QtWidgets.QVBoxLayout()
        self.body.setContentsMargins(-1, -1, -1, 0)
        self.body.setObjectName("body")
        self.scrollArea = QtWidgets.QScrollArea(self.layoutWidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(929, 539))
        self.scrollArea.setStyleSheet("border-radius:10px\n"
"")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setLineWidth(2)
        self.scrollArea.setWidgetResizable(False)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 929, 539))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(0, 539))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777213))
        self.scrollAreaWidgetContents.setStyleSheet("border-radius:10px;\n"
"border:0px;\n"
"")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 10, 861, 81))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.contents_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.contents_layout.setContentsMargins(0, 0, 0, 0)
        self.contents_layout.setHorizontalSpacing(7)
        self.contents_layout.setVerticalSpacing(15)
        self.contents_layout.setObjectName("contents_layout")
        self.single_container = QtWidgets.QGridLayout()
        self.single_container.setHorizontalSpacing(12)
        self.single_container.setVerticalSpacing(5)
        self.single_container.setObjectName("single_container")
        self.code_layout = QtWidgets.QHBoxLayout()
        self.code_layout.setSpacing(0)
        self.code_layout.setObjectName("code_layout")
        self.code_field_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.code_field_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.code_field_1.sizePolicy().hasHeightForWidth())
        self.code_field_1.setSizePolicy(sizePolicy)
        self.code_field_1.setMinimumSize(QtCore.QSize(0, 30))
        self.code_field_1.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.code_field_1.setStyleSheet("QLineEdit { text-align: center;border-top-right-radius:0px; border-bottom-right-radius:0px}\n"
"")
        self.code_field_1.setText("")
        self.code_field_1.setObjectName("code_field_1")
        self.code_layout.addWidget(self.code_field_1)
        self.code_copy_but_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.code_copy_but_1.setMinimumSize(QtCore.QSize(130, 30))
        self.code_copy_but_1.setMaximumSize(QtCore.QSize(119, 16777215))
        self.code_copy_but_1.setStyleSheet("border-top-left-radius:0px; border-bottom-left-radius:0px")
        self.code_copy_but_1.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.code_copy_but_1.setIcon(icon)
        self.code_copy_but_1.setObjectName("code_copy_but_1")
        self.code_layout.addWidget(self.code_copy_but_1)
        self.single_container.addLayout(self.code_layout, 0, 2, 1, 1)
        self.country_service_layout = QtWidgets.QHBoxLayout()
        self.country_service_layout.setContentsMargins(10, -1, 10, -1)
        self.country_service_layout.setObjectName("country_service_layout")
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_1.sizePolicy().hasHeightForWidth())
        self.label_1.setSizePolicy(sizePolicy)
        self.label_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_1.setObjectName("label_1")
        self.country_service_layout.addWidget(self.label_1)
        self.country_name_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.country_name_1.setMinimumSize(QtCore.QSize(210, 0))
        self.country_name_1.setText("")
        self.country_name_1.setObjectName("country_name_1")
        self.country_service_layout.addWidget(self.country_name_1)
        self.label_2_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2_1.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_2_1.setObjectName("label_2_1")
        self.country_service_layout.addWidget(self.label_2_1)
        self.servic_name_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.servic_name_1.setMinimumSize(QtCore.QSize(100, 0))
        self.servic_name_1.setText("")
        self.servic_name_1.setObjectName("servic_name_1")
        self.country_service_layout.addWidget(self.servic_name_1)
        self.single_container.addLayout(self.country_service_layout, 2, 0, 1, 1)
        self.number_layout = QtWidgets.QHBoxLayout()
        self.number_layout.setSpacing(0)
        self.number_layout.setObjectName("number_layout")
        self.number_field_1 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.number_field_1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.number_field_1.sizePolicy().hasHeightForWidth())
        self.number_field_1.setSizePolicy(sizePolicy)
        self.number_field_1.setMinimumSize(QtCore.QSize(350, 30))
        self.number_field_1.setMaximumSize(QtCore.QSize(200, 16777215))
        self.number_field_1.setStyleSheet("QLineEdit { text-align: center;border-top-right-radius:0px; border-bottom-right-radius:0px}\n"
"")
        self.number_field_1.setText("")
        self.number_field_1.setObjectName("number_field_1")
        self.number_layout.addWidget(self.number_field_1)
        self.number_copy_btn_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.number_copy_btn_1.sizePolicy().hasHeightForWidth())
        self.number_copy_btn_1.setSizePolicy(sizePolicy)
        self.number_copy_btn_1.setMinimumSize(QtCore.QSize(80, 30))
        self.number_copy_btn_1.setMaximumSize(QtCore.QSize(150, 30))
        self.number_copy_btn_1.setStyleSheet("border-top-left-radius:0px; border-bottom-left-radius:0px")
        self.number_copy_btn_1.setText("")
        self.number_copy_btn_1.setIcon(icon)
        self.number_copy_btn_1.setObjectName("number_copy_btn_1")
        self.number_layout.addWidget(self.number_copy_btn_1)
        self.single_container.addLayout(self.number_layout, 0, 0, 1, 1)
        self.status_cancel_layout = QtWidgets.QHBoxLayout()
        self.status_cancel_layout.setContentsMargins(10, -1, 10, -1)
        self.status_cancel_layout.setObjectName("status_cancel_layout")
        self.code_status_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.code_status_1.setStyleSheet("")
        self.code_status_1.setObjectName("code_status_1")
        self.status_cancel_layout.addWidget(self.code_status_1)
        self.cancel_number_but_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.cancel_number_but_1.setMinimumSize(QtCore.QSize(40, 30))
        self.cancel_number_but_1.setMaximumSize(QtCore.QSize(30, 30))
        self.cancel_number_but_1.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("cancel.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cancel_number_but_1.setIcon(icon1)
        self.cancel_number_but_1.setObjectName("cancel_number_but_1")
        self.status_cancel_layout.addWidget(self.cancel_number_but_1)
        self.single_container.addLayout(self.status_cancel_layout, 2, 2, 1, 1)
        self.contents_layout.addLayout(self.single_container, 1, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(self.scrollAreaWidgetContents)
        self.listWidget.setGeometry(QtCore.QRect(20, 310, 201, 231))
        self.listWidget.setStyleSheet("QListWidget{background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"color:white}\n"
"QScrollBar:vertical {\n"
"                width: 8px;\n"
"                background: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));;\n"
"            }\n"
"\n"
"            QScrollBar::handle:vertical {\n"
"                background: grey;\n"
"                min-height: 20px;\n"
"            }\n"
"\n"
"            QScrollBar::handle:vertical:hover {\n"
"                background: #777;\n"
"            }\n"
"\n"
"            QScrollBar::add-line:vertical,\n"
"            QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"            }\n"
"\n"
"            QScrollBar::add-page:vertical,\n"
"            QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.pass_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.pass_widget.setGeometry(QtCore.QRect(390, 450, 421, 41))
        self.pass_widget.setStyleSheet("QWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 200), stop:1 rgba(120, 120, 130, 200));\n"
"}")
        self.pass_widget.setObjectName("pass_widget")
        self.label_8 = QtWidgets.QLabel(self.pass_widget)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 81, 20))
        self.label_8.setStyleSheet("background-color:none")
        self.label_8.setObjectName("label_8")
        self.password_field = QtWidgets.QLineEdit(self.pass_widget)
        self.password_field.setGeometry(QtCore.QRect(80, 10, 201, 20))
        self.password_field.setStyleSheet("background-color:grey")
        self.password_field.setText("")
        self.password_field.setObjectName("password_field")
        self.access_setting_but = QtWidgets.QPushButton(self.pass_widget)
        self.access_setting_but.setGeometry(QtCore.QRect(292, 5, 121, 30))
        self.access_setting_but.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"border:0\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"\n"
"")
        self.access_setting_but.setObjectName("access_setting_but")
        self.settings_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.settings_widget.setGeometry(QtCore.QRect(390, 260, 421, 231))
        self.settings_widget.setStyleSheet("QWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 200), stop:1 rgba(120, 120, 130, 200));\n"
"}")
        self.settings_widget.setObjectName("settings_widget")
        self.label_9 = QtWidgets.QLabel(self.settings_widget)
        self.label_9.setGeometry(QtCore.QRect(20, 60, 71, 20))
        self.label_9.setStyleSheet("background-color:none")
        self.label_9.setObjectName("label_9")
        self.api_field = QtWidgets.QLineEdit(self.settings_widget)
        self.api_field.setGeometry(QtCore.QRect(90, 60, 311, 20))
        self.api_field.setStyleSheet("background-color:grey")
        self.api_field.setText("")
        self.api_field.setObjectName("api_field")
        self.setting_save_but = QtWidgets.QPushButton(self.settings_widget)
        self.setting_save_but.setGeometry(QtCore.QRect(100, 190, 101, 30))
        self.setting_save_but.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"border:0\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"\n"
"")
        self.setting_save_but.setObjectName("setting_save_but")
        self.label_10 = QtWidgets.QLabel(self.settings_widget)
        self.label_10.setGeometry(QtCore.QRect(20, 90, 71, 20))
        self.label_10.setStyleSheet("background-color:none")
        self.label_10.setObjectName("label_10")
        self.max_cost_field = QtWidgets.QLineEdit(self.settings_widget)
        self.max_cost_field.setGeometry(QtCore.QRect(90, 90, 311, 20))
        self.max_cost_field.setStyleSheet("background-color:grey")
        self.max_cost_field.setText("")
        self.max_cost_field.setObjectName("max_cost_field")
        self.setting_cancel_but = QtWidgets.QPushButton(self.settings_widget)
        self.setting_cancel_but.setGeometry(QtCore.QRect(240, 190, 101, 30))
        self.setting_cancel_but.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"border:0\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"\n"
"")
        self.setting_cancel_but.setObjectName("setting_cancel_but")
        self.label_15 = QtWidgets.QLabel(self.settings_widget)
        self.label_15.setGeometry(QtCore.QRect(190, 10, 71, 20))
        self.label_15.setStyleSheet("background-color:none")
        self.label_15.setObjectName("label_15")
        self.password_change_field = QtWidgets.QLineEdit(self.settings_widget)
        self.password_change_field.setGeometry(QtCore.QRect(90, 120, 311, 20))
        self.password_change_field.setStyleSheet("background-color:grey")
        self.password_change_field.setText("")
        self.password_change_field.setObjectName("password_change_field")
        self.label_18 = QtWidgets.QLabel(self.settings_widget)
        self.label_18.setGeometry(QtCore.QRect(20, 120, 71, 20))
        self.label_18.setStyleSheet("background-color:none")
        self.label_18.setObjectName("label_18")
        self.saved_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.saved_widget.setGeometry(QtCore.QRect(390, 260, 421, 231))
        self.saved_widget.setStyleSheet("QWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 200), stop:1 rgba(120, 120, 130, 200));\n"
"}")
        self.saved_widget.setObjectName("saved_widget")
        self.label_21 = QtWidgets.QLabel(self.saved_widget)
        self.label_21.setGeometry(QtCore.QRect(160, 110, 101, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("background-color:none")
        self.label_21.setObjectName("label_21")
        self.cancel_confirm = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.cancel_confirm.setGeometry(QtCore.QRect(480, 55, 381, 30))
        self.cancel_confirm.setStyleSheet("QWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 255), stop:1 rgba(120, 120, 130, 255));\n"
"}")
        self.cancel_confirm.setObjectName("cancel_confirm")
        self.label = QtWidgets.QLabel(self.cancel_confirm)
        self.label.setGeometry(QtCore.QRect(10, 5, 171, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:none")
        self.label.setObjectName("label")
        self.cancel_confirm_but = QtWidgets.QPushButton(self.cancel_confirm)
        self.cancel_confirm_but.setGeometry(QtCore.QRect(180, 0, 130, 30))
        self.cancel_confirm_but.setMinimumSize(QtCore.QSize(130, 30))
        self.cancel_confirm_but.setMaximumSize(QtCore.QSize(30, 30))
        self.cancel_confirm_but.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(80, 80, 80, 255), stop:1 rgba(80, 80, 80, 255));\n"
"border:0;\n"
"color:red;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:0\n"
"}\n"
"\n"
"border-radius:15px;\n"
"border:0;")
        self.cancel_confirm_but.setObjectName("cancel_confirm_but")
        self.close_cancel_widget = QtWidgets.QPushButton(self.cancel_confirm)
        self.close_cancel_widget.setGeometry(QtCore.QRect(340, 0, 40, 30))
        self.close_cancel_widget.setMinimumSize(QtCore.QSize(40, 30))
        self.close_cancel_widget.setMaximumSize(QtCore.QSize(30, 30))
        self.close_cancel_widget.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:1px white solid;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 200), stop:1 rgba(120, 120, 130, 200));\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(107, 107, 107, 255), stop:1 rgba(157, 157, 157, 255));\n"
"border:1px white solid;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:1px white solid;\n"
"}")
        self.close_cancel_widget.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("cancel2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_cancel_widget.setIcon(icon2)
        self.close_cancel_widget.setObjectName("close_cancel_widget")
        self.number_notification = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.number_notification.setGeometry(QtCore.QRect(240, 450, 431, 41))
        self.number_notification.setStyleSheet("QWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 200), stop:1 rgba(120, 120, 130, 200));\n"
"}\n"
"QLabel { qproperty-alignment: AlignCenter; }")
        self.number_notification.setObjectName("number_notification")
        self.number_notify_text = QtWidgets.QLabel(self.number_notification)
        self.number_notify_text.setGeometry(QtCore.QRect(-10, 10, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.number_notify_text.setFont(font)
        self.number_notify_text.setStyleSheet("background-color:none;\n"
"QLabel { qproperty-alignment: AlignCenter; }")
        self.number_notify_text.setObjectName("number_notify_text")
        self.close_notify = QtWidgets.QPushButton(self.number_notification)
        self.close_notify.setGeometry(QtCore.QRect(390, 0, 40, 41))
        self.close_notify.setMinimumSize(QtCore.QSize(40, 41))
        self.close_notify.setMaximumSize(QtCore.QSize(30, 30))
        self.close_notify.setStyleSheet("QPushButton{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:1px white solid;\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 200), stop:1 rgba(125, 125, 125, 200));\n"
"}\n"
"QPushButton:hover{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(180, 180, 180, 255), stop:1 rgba(110, 110, 110, 255));\n"
"    border-bottom-color: rgb(115, 115, 115);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(100, 100, 100, 200), stop:1 rgba(110, 110, 110, 200));\n"
"border:1px white solid;\n"
"}\n"
"QPushButton:pressed{\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:0.6, x2:0.5, y2:0.4, stop:0 rgba(62, 62, 62, 255), stop:1 rgba(22, 22, 22, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:0.4, y1:0.5, x2:0.6, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0.6, y1:0.5, x2:0.4, y2:0.5, stop:0 rgba(115, 115, 115, 255), stop:1 rgba(62, 62, 62, 255));\n"
"    border-bottom-color: rgb(58, 58, 58);\n"
"    border-bottom-width: 1px;\n"
"    border-style: solid;\n"
"    color: rgb(255, 255, 255);\n"
"    padding: 2px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 255), stop:1 rgba(97, 97, 97, 255));\n"
"border:1px white solid;\n"
"}")
        self.close_notify.setText("")
        self.close_notify.setIcon(icon2)
        self.close_notify.setObjectName("close_notify")
        self.body_widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.body_widget.setGeometry(QtCore.QRect(-50, -50, 1021, 711))
        self.body_widget.setMinimumSize(QtCore.QSize(0, 200))
        self.body_widget.setStyleSheet("QWidget{\n"
"background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(160, 160, 160, 50), stop:1 rgba(160, 160, 160, 50));\n"
"}\n"
"\n"
"alignment: AlignCenter;")
        self.body_widget.setObjectName("body_widget")
        self.label_25 = QtWidgets.QLabel(self.body_widget)
        self.label_25.setGeometry(QtCore.QRect(310, 320, 371, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("background-color:none;\n"
"\n"
"\n"
"qproperty-alignment: AlignCenter;")
        self.label_25.setObjectName("label_25")
        self.body_widget.raise_()
        self.saved_widget.raise_()
        self.pass_widget.raise_()
        self.settings_widget.raise_()
        self.gridLayoutWidget.raise_()
        self.listWidget.raise_()
        self.number_notification.raise_()
        self.cancel_confirm.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.body.addWidget(self.scrollArea)
        self.main_layout.addLayout(self.body, 2, 0, 1, 1)
        self.header = QtWidgets.QHBoxLayout()
        self.header.setContentsMargins(30, 40, -1, -1)
        self.header.setObjectName("header")
        self.label_secret = QtWidgets.QLabel(self.layoutWidget)
        self.label_secret.setMinimumSize(QtCore.QSize(480, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_secret.setFont(font)
        self.label_secret.setObjectName("label_secret")
        self.header.addWidget(self.label_secret)
        self.label_otp = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_otp.setFont(font)
        self.label_otp.setObjectName("label_otp")
        self.header.addWidget(self.label_otp)
        self.main_layout.addLayout(self.header, 0, 0, 1, 1)
        self.contents_layout_2 = QtWidgets.QGridLayout()
        self.contents_layout_2.setContentsMargins(0, 0, -1, -1)
        self.contents_layout_2.setHorizontalSpacing(5)
        self.contents_layout_2.setVerticalSpacing(10)
        self.contents_layout_2.setObjectName("contents_layout_2")
        self.secret_field_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.secret_field_1.setMinimumSize(QtCore.QSize(600, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.secret_field_1.setFont(font)
        self.secret_field_1.setStyleSheet("\n"
"border-radius:15px;\n"
"border:none;")
        self.secret_field_1.setText("")
        self.secret_field_1.setObjectName("secret_field_1")
        self.contents_layout_2.addWidget(self.secret_field_1, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.otp_field_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.otp_field_1.setEnabled(True)
        self.otp_field_1.setMinimumSize(QtCore.QSize(180, 30))
        self.otp_field_1.setMaximumSize(QtCore.QSize(80, 16777215))
        self.otp_field_1.setStyleSheet("\n"
"border-radius:15px;\n"
"border:none;\n"
"border-top-right-radius:0px; border-bottom-right-radius:0px;")
        self.otp_field_1.setText("")
        self.otp_field_1.setObjectName("otp_field_1")
        self.horizontalLayout.addWidget(self.otp_field_1)
        self.copy_button_1 = QtWidgets.QPushButton(self.layoutWidget)
        self.copy_button_1.setMinimumSize(QtCore.QSize(60, 30))
        self.copy_button_1.setStyleSheet("border-radius:15px;\n"
"border:none;\n"
"border-top-left-radius:0px; border-bottom-left-radius:0px")
        self.copy_button_1.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("D:/Work/UpWork/Authenticator G Sheet/App/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_button_1.setIcon(icon3)
        self.copy_button_1.setObjectName("copy_button_1")
        self.horizontalLayout.addWidget(self.copy_button_1)
        self.contents_layout_2.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.main_layout.addLayout(self.contents_layout_2, 3, 0, 1, 1)
        self.bottom_line = QtWidgets.QHBoxLayout()
        self.bottom_line.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.bottom_line.setContentsMargins(0, 20, 0, 20)
        self.bottom_line.setSpacing(0)
        self.bottom_line.setObjectName("bottom_line")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setMinimumSize(QtCore.QSize(20, 0))
        self.label_6.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.bottom_line.addWidget(self.label_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.service_field = QtWidgets.QLineEdit(self.layoutWidget)
        self.service_field.setMinimumSize(QtCore.QSize(0, 30))
        self.service_field.setMaximumSize(QtCore.QSize(200, 16777215))
        self.service_field.setStyleSheet("border-radius:10px\n"
"")
        self.service_field.setInputMask("")
        self.service_field.setText("")
        self.service_field.setObjectName("service_field")
        self.verticalLayout.addWidget(self.service_field)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setMaximumSize(QtCore.QSize(200, 20))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.listWidget_2 = QtWidgets.QListWidget(self.layoutWidget)
        self.listWidget_2.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget_2.setMaximumSize(QtCore.QSize(50, 60))
        self.listWidget_2.setStyleSheet("QListWidget{background-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 50), stop:1 rgba(97, 97, 97, 50));\n"
"color:white}\n"
"QScrollBar:vertical {\n"
"                width: 8px;\n"
"                background: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(77, 77, 77, 50), stop:1 rgba(97, 97, 97, 50));;\n"
"            }\n"
"\n"
"            QScrollBar::handle:vertical {\n"
"                background: grey;\n"
"                min-height: 20px;\n"
"            }\n"
"\n"
"            QScrollBar::handle:vertical:hover {\n"
"                background: #777;\n"
"            }\n"
"\n"
"            QScrollBar::add-line:vertical,\n"
"            QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"            }\n"
"\n"
"            QScrollBar::add-page:vertical,\n"
"            QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }")
        self.listWidget_2.setObjectName("listWidget_2")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_2.addItem(item)
        self.verticalLayout.addWidget(self.listWidget_2)
        self.bottom_line.addLayout(self.verticalLayout)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setMaximumSize(QtCore.QSize(30, 16777215))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.bottom_line.addWidget(self.label_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.messages = QtWidgets.QLabel(self.layoutWidget)
        self.messages.setMinimumSize(QtCore.QSize(300, 0))
        self.messages.setMaximumSize(QtCore.QSize(350, 16777215))
        self.messages.setStyleSheet("QLabel { qproperty-alignment: AlignCenter;\n"
"margin-left:50px;\n"
" }\n"
"")
        self.messages.setObjectName("messages")
        self.verticalLayout_2.addWidget(self.messages)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.timesNumber = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.timesNumber.sizePolicy().hasHeightForWidth())
        self.timesNumber.setSizePolicy(sizePolicy)
        self.timesNumber.setMinimumSize(QtCore.QSize(0, 0))
        self.timesNumber.setMaximumSize(QtCore.QSize(30, 30))
        self.timesNumber.setStyleSheet("")
        self.timesNumber.setObjectName("timesNumber")
        self.horizontalLayout_3.addWidget(self.timesNumber)
        self.update_butt = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.update_butt.sizePolicy().hasHeightForWidth())
        self.update_butt.setSizePolicy(sizePolicy)
        self.update_butt.setMinimumSize(QtCore.QSize(300, 50))
        self.update_butt.setMaximumSize(QtCore.QSize(3000, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.update_butt.setFont(font)
        self.update_butt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.update_butt.setStyleSheet("border-radius:25;\n"
"border:0px;\n"
"")
        self.update_butt.setCheckable(False)
        self.update_butt.setDefault(False)
        self.update_butt.setFlat(False)
        self.update_butt.setObjectName("update_butt")
        self.horizontalLayout_3.addWidget(self.update_butt)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(160, -1, -1, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setMinimumSize(QtCore.QSize(55, 20))
        self.label_16.setMaximumSize(QtCore.QSize(55, 30))
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_5.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_5.addWidget(self.label_17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.bottom_line.addLayout(self.verticalLayout_2)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setMinimumSize(QtCore.QSize(80, 0))
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.bottom_line.addWidget(self.label_4)
        self.setting_button = QtWidgets.QPushButton(self.layoutWidget)
        self.setting_button.setMinimumSize(QtCore.QSize(50, 30))
        self.setting_button.setMaximumSize(QtCore.QSize(30, 30))
        self.setting_button.setStyleSheet("border-radius:15px;\n"
"border:0")
        self.setting_button.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setting_button.setIcon(icon4)
        self.setting_button.setObjectName("setting_button")
        self.bottom_line.addWidget(self.setting_button)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(60, 0))
        self.label_7.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_7.setStyleSheet("")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.bottom_line.addWidget(self.label_7)
        self.close_button = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setMinimumSize(QtCore.QSize(100, 0))
        self.close_button.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.close_button.setFont(font)
        self.close_button.setStyleSheet("border-radius:15px;\n"
"border:0px;\n"
"")
        self.close_button.setObjectName("close_button")
        self.bottom_line.addWidget(self.close_button)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.bottom_line.addWidget(self.label_3)
        self.main_layout.addLayout(self.bottom_line, 4, 0, 1, 1)
        self.balance_widget = QtWidgets.QPushButton(otpwin)
        self.balance_widget.setGeometry(QtCore.QRect(470, 800, 111, 31))
        self.balance_widget.setStyleSheet("background-color:none;\n"
"border:none")
        self.balance_widget.setText("")
        self.balance_widget.setObjectName("balance_widget")

        self.retranslateUi(otpwin)
        QtCore.QMetaObject.connectSlotsByName(otpwin)

    def retranslateUi(self, otpwin):
        _translate = QtCore.QCoreApplication.translate
        otpwin.setWindowTitle(_translate("otpwin", "Dialog"))
        self.label_1.setText(_translate("otpwin", "Country:"))
        self.label_2_1.setText(_translate("otpwin", "Service:"))
        self.code_status_1.setText(_translate("otpwin", "Code_status"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("otpwin", "cxvxcv"))
        item = self.listWidget.item(1)
        item.setText(_translate("otpwin", "dvc"))
        item = self.listWidget.item(2)
        item.setText(_translate("otpwin", "cv"))
        item = self.listWidget.item(3)
        item.setText(_translate("otpwin", "c"))
        item = self.listWidget.item(4)
        item.setText(_translate("otpwin", "v"))
        item = self.listWidget.item(5)
        item.setText(_translate("otpwin", "xcvxcv"))
        item = self.listWidget.item(6)
        item.setText(_translate("otpwin", "xc"))
        item = self.listWidget.item(7)
        item.setText(_translate("otpwin", "v"))
        item = self.listWidget.item(8)
        item.setText(_translate("otpwin", "xcv"))
        item = self.listWidget.item(9)
        item.setText(_translate("otpwin", "xc"))
        item = self.listWidget.item(10)
        item.setText(_translate("otpwin", "v"))
        item = self.listWidget.item(11)
        item.setText(_translate("otpwin", "cx"))
        item = self.listWidget.item(12)
        item.setText(_translate("otpwin", "v"))
        item = self.listWidget.item(13)
        item.setText(_translate("otpwin", "xc"))
        item = self.listWidget.item(14)
        item.setText(_translate("otpwin", "v"))
        item = self.listWidget.item(15)
        item.setText(_translate("otpwin", "xc"))
        item = self.listWidget.item(16)
        item.setText(_translate("otpwin", "v"))
        item = self.listWidget.item(17)
        item.setText(_translate("otpwin", "xcv"))
        item = self.listWidget.item(18)
        item.setText(_translate("otpwin", "New Item"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.label_8.setText(_translate("otpwin", "Password:"))
        self.access_setting_but.setText(_translate("otpwin", "Access Settings"))
        self.label_9.setText(_translate("otpwin", "API KEY"))
        self.api_field.setPlaceholderText(_translate("otpwin", "Key From your Profile"))
        self.setting_save_but.setText(_translate("otpwin", "Save Settings"))
        self.label_10.setText(_translate("otpwin", "MAX COST"))
        self.max_cost_field.setPlaceholderText(_translate("otpwin", "Number"))
        self.setting_cancel_but.setText(_translate("otpwin", "Cancel"))
        self.label_15.setText(_translate("otpwin", "Settings"))
        self.password_change_field.setPlaceholderText(_translate("otpwin", "Min 6 Characters"))
        self.label_18.setText(_translate("otpwin", "Password"))
        self.label_21.setText(_translate("otpwin", "Settings Saved"))
        self.label.setText(_translate("otpwin", "Cancel this number?"))
        self.cancel_confirm_but.setText(_translate("otpwin", "Cancel Number"))
        self.number_notify_text.setText(_translate("otpwin", "Number 201559660120 Created for  0.05$"))
        self.label_25.setText(_translate("otpwin", "Loading ..."))
        self.label_secret.setText(_translate("otpwin", "Number"))
        self.label_otp.setText(_translate("otpwin", "Code"))
        self.secret_field_1.setPlaceholderText(_translate("otpwin", "Secret"))
        self.otp_field_1.setPlaceholderText(_translate("otpwin", "OTP"))
        self.service_field.setPlaceholderText(_translate("otpwin", "Service"))
        self.label_2.setText(_translate("otpwin", "Target Price Countries"))
        __sortingEnabled = self.listWidget_2.isSortingEnabled()
        self.listWidget_2.setSortingEnabled(False)
        item = self.listWidget_2.item(0)
        item.setText(_translate("otpwin", "Indonesia"))
        item = self.listWidget_2.item(1)
        item.setText(_translate("otpwin", "Latvia"))
        self.listWidget_2.setSortingEnabled(__sortingEnabled)
        self.messages.setText(_translate("otpwin", "Getting Current Status and Available Numbers"))
        self.timesNumber.setText(_translate("otpwin", "1"))
        self.update_butt.setText(_translate("otpwin", "Get New Number"))
        self.label_16.setText(_translate("otpwin", "Balance:"))
        self.close_button.setText(_translate("otpwin", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    otpwin = QtWidgets.QDialog()
    ui = Ui_otpwin()
    ui.setupUi(otpwin)
    otpwin.show()
    sys.exit(app.exec_())
